[project]
name = "log-tools"
version = "0.1.0"
description = "Various python logging tools for internal Trilobio use."
authors = []
readme = "README.md"
packages = [{include = "log_tools"}]
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.11"
dependencies = [
    "plac>=1.4.5",
    "python-json-logger>=3.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poetry.group.dev]
optional = true

[tool.poetry.scripts]
test = "tests:main"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"
mypy = "^1.11.1"
ruff = "^0.1.0"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100
