[project]
name = "aceta"
version = "0.1.0"
description = "Aceta"
authors = []
readme = "README.md"
requires-python = ">=3.11"


[tool.uv.workspace]
members = [
    "core",
    "can_bus",
    "can-relay",
    "config-tools",
    "firmware-tools",
    "log-tools",
    "robot",
    "scale",
    "tcode",
    "test-fixture",
    "path_planner"
]

[tool.uv.sources]
tcode-api = { git = "ssh://git@github.com/trilobio/tcode-api.git", rev = "v1.10.1" }
transform-tree = { git = "ssh://git@github.com/trilobio/transform-tree.git", rev = "v2.6.0" }
aceta-grpc = { git = "ssh://git@github.com/trilobio/grpc.git", rev = "v1.0.0" }

can-relay = { workspace = true }
can-bus = { workspace = true }
config-tools = { workspace = true }
core = { workspace = true }
log-tools = { workspace = true }
path-planner = { workspace = true }
robot = { workspace = true }
firmware-tools = { workspace = true }
