[project]
name = "py-organelles"
version = "1.4.0"
description = "Small yet vital python tools found in all Trilobio python projects"
authors = []
readme = "README.md"
packages = [{include = "py_organelles"}]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "pint>=0.25.3",
    "plac>=1.4.5",
    "pydantic>=2.13.3",
    "python-json-logger>=4.0.0",
    "rich>=14.0.0",
    "wrapt",
]

[dependency-groups]
dev = [
    "coverage>=7.8.2",
    "ipython>=9.7.0",
    "mypy>=1.19.0",
    "ruff>=0.11.5",
    "scipy>=1.17.1",  # Used for unittesting the core.transform submodule using scipy.spatial.Rotationq
    "scipy-stubs>=1.17.1.4",
]

[tool.mypy]
# https://adamj.eu/tech/2021/05/25/python-type-hints-specific-type-ignore/
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
# PLC0415 = Local import at the top of the file
# Added at the behest of Claude to catch the AI anti-pattern of liberally mixing imports throughout
# the file instead of grouping them at the top.
# Seeing this issue erroneously cause you're deliberately using a local import?
# Use `# noqa: PLC0415` to ignore this check for the specific line.
# F = pyflakes
# I = isort
# RUF022 = sort __all__ lists
select = ["PLC0415", "F", "I", "RUF022"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
