[project]
name = "py-organelles"
version = "0.1.0"
description = "Small yet vital python tools found in all Trilobio python projects"
authors = []
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "plac>=1.4.5",
    "python-json-logger>=4.0.0",
    "wrapt>=2.0.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "coverage>=7.8.2",
    "ipython>=9.1.0",
    "isort>=6.0.1",
    "mypy>=1.19.0",
    "ptpython>=3.0.30",
    "ruff>=0.11.5",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
# https://adamj.eu/tech/2021/05/25/python-type-hints-specific-type-ignore/
show_error_codes = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.ruff]
line-length = 100
