"""Registration and lookup errors raised by the object factories.

.. note:: Generated by Claude Opus 5.
"""

import unittest

from py_organelles import BuilderExistsError, BuilderNotFoundError, ObjectFactory
from py_organelles.core.factory import MultiBuilderObjectFactory


class TestObjectFactory(unittest.TestCase):
    """.. note:: Generated by Claude Opus 5."""

    def setUp(self) -> None:
        self.factory = ObjectFactory("TestFactory")
        self.factory.register_builder("a", lambda: "built-a")

    def test_duplicate_registration_raises(self) -> None:
        with self.assertRaises(BuilderExistsError) as ctx:
            self.factory.register_builder("a", lambda: "other")
        self.assertEqual(ctx.exception.factory_key, "a")
        self.assertIn("a", ctx.exception.builder_keys)

    def test_override_replaces(self) -> None:
        self.factory.register_builder("a", lambda: "replaced", override=True)
        self.assertEqual(self.factory.create("a"), "replaced")

    def test_missing_builder_reports_what_was_available(self) -> None:
        """The error names the factory, the key asked for, and the keys it had."""
        with self.assertRaises(BuilderNotFoundError) as ctx:
            self.factory.create("nope")
        self.assertEqual(ctx.exception.factory_name, "TestFactory")
        self.assertEqual(ctx.exception.factory_key, "nope")
        self.assertEqual(ctx.exception.builder_keys, ["a"])
        self.assertIn("TestFactory", str(ctx.exception))
        self.assertIn("nope", str(ctx.exception))


class TestMultiBuilderObjectFactory(unittest.TestCase):
    """.. note:: Generated by Claude Opus 5."""

    def setUp(self) -> None:
        self.factory = MultiBuilderObjectFactory(["from_thing"], name="MultiFactory")
        self.factory.register_builder("from_thing", "a", lambda: "built-a")

    def test_duplicate_registration_raises(self) -> None:
        """The regression: this check read the outer dict, so a duplicate key never matched.

        ``self._builders`` is keyed by *builder kind*, so ``key in self._builders`` asked
        whether the key happened to name a kind. It never did, so a second registration
        silently replaced the first - the opposite of what ``override=False`` promises.
        """
        with self.assertRaises(BuilderExistsError) as ctx:
            self.factory.register_builder("from_thing", "a", lambda: "other")
        self.assertEqual(ctx.exception.factory_key, "a")

    def test_duplicate_registration_does_not_overwrite(self) -> None:
        """What the silent overwrite actually cost: the first builder was lost."""
        with self.assertRaises(BuilderExistsError):
            self.factory.register_builder("from_thing", "a", lambda: "other")
        self.assertEqual(self.factory.build("from_thing", "a"), "built-a")

    def test_a_key_matching_a_builder_kind_is_still_registrable(self) -> None:
        """The old check would have rejected this one, for the wrong reason."""
        self.factory.register_builder("from_thing", "from_thing", lambda: "built-kindname")
        self.assertEqual(self.factory.build("from_thing", "from_thing"), "built-kindname")

    def test_override_replaces(self) -> None:
        self.factory.register_builder("from_thing", "a", lambda: "replaced", override=True)
        self.assertEqual(self.factory.build("from_thing", "a"), "replaced")

    def test_missing_builder_reports_what_was_available(self) -> None:
        with self.assertRaises(BuilderNotFoundError) as ctx:
            self.factory.build("from_thing", "nope")
        self.assertEqual(ctx.exception.factory_key, "nope")
        self.assertEqual(ctx.exception.builder_keys, ["a"])
