[project]
name = "core"
version = "0.2.0"
description = "Generic structures for writing Python at Trilobio."
authors = [{ name = "Connor Novak", email = "connor@trilo.bio" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plac>=1.4.5",
    "wrapt>=1.17.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
