[tool.poetry]
name = "core"
version = "0.1.0"
description = "Generic structures for writing Python at Trilobio."
authors = ["Connor Novak <connor@trilo.bio>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <=3.12"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
ruff = "^0.1.14"
isort = "^5.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
